 name: Unit Tests

 on:
   push:
     branches: ["master"]
   pull:
     branches: ["master"]
   workflow_dispatch:

   needs: [lint]
   runs-on: ubuntu-latest
   steps:
     - name: Checkout the code
       uses: actions/checkout@v2

     - name: Run Tests
       run: ./gradlew test

     - name: Upload Test Report
       uses: actions/upload-artifact@v2
       with:
         name: unit_test_report
         path: app/build/reports/tests/testDebugUnitTest/

